---
- name: Setting var file
  hosts: redis
  remote_user: dmaksakov
  become: yes
  tasks:
    - name: Collecting IPs
      lineinfile:
        line: "{{ inventory_hostname_short }}{{':'}} {{ ansible_eth0.ipv4.address }}"
        path: "{{ playbook_dir }}/ips.yml"
        create: yes
      delegate_to: 127.0.0.1
      tags: get-ips

- name: Redis Cluster Install
  remote_user: dmaksakov
  hosts: redis
  become: yes
  gather_facts: no
  tasks:
    - name: Download redis.rpm file
      get_url:
        url: https://rpmfind.net/linux/centos/8.4.2105/AppStream/x86_64/os/Packages/redis-6.0.9-3.module_el8.4.0+788+86a4d8e8.x86_64.rpm
        dest: /tmp/
        mode: "0644"

    - name: install redis
      yum:
        name: /tmp/redis-6.0.9-3.module_el8.4.0+788+86a4d8e8.x86_64.rpm
        state: present

    - name: Swappoff disable
      command: swapoff -a
      ignore_errors: yes

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Redis.conf backup
      command: mv /etc/redis.conf /etc/redis_backup.conf
      ignore_errors: yes

    - name: Download redis.rpm file
      copy:
        src: "{{ playbook_dir }}/redis.conf"
        dest: /etc/
        mode: "0755"

    - name: Upload service
      copy:
        src: "{{ playbook_dir }}/redis.service"
        dest: /usr/lib/systemd/system/redis.service

- name: Redis Cluster Install
  hosts: redis-1
  remote_user: dmaksakov
  become: yes
  gather_facts: no
  tasks:
    - name: Loading hosts vars
      include_vars:
        file: "{{ playbook_dir }}/ips.yml"
        name: hosts

    - name: Insert configuration bind section
      lineinfile:
        path: /etc/redis.conf
        regexp: "bind 127.0.0.1"
        line: "bind {{ hosts['redis-1'] }}"

- name: Redis Cluster Install
  hosts: redis-2
  remote_user: dmaksakov
  become: yes
  gather_facts: no
  tasks:
    - name: Loading hosts vars
      include_vars:
        file: "{{ playbook_dir }}/ips.yml"
        name: hosts

    - name: Insert configuration bind section
      lineinfile:
        path: /etc/redis.conf
        regexp: "bind 127.0.0.1"
        line: "bind {{ hosts['redis-2'] }}"

- name: Redis Cluster Install
  hosts: redis-3
  become: yes
  remote_user: dmaksakov
  gather_facts: no
  tasks:
    - name: Loading hosts vars
      include_vars:
        file: "{{ playbook_dir }}/ips.yml"
        name: hosts

    - name: Insert configuration bind section
      lineinfile:
        path: /etc/redis.conf
        regexp: "bind 127.0.0.1"
        line: "bind {{ hosts['redis-3'] }}"

- name: Redis Cluster Install
  hosts: redis-4
  become: yes
  remote_user: dmaksakov
  gather_facts: no
  tasks:
    - name: Loading hosts vars
      include_vars:
        file: "{{ playbook_dir }}/ips.yml"
        name: hosts

    - name: Insert configuration bind section
      lineinfile:
        path: /etc/redis.conf
        regexp: "bind 127.0.0.1"
        line: "bind {{ hosts['redis-4'] }}"

- name: Redis Cluster Install
  hosts: redis-5
  become: yes
  remote_user: dmaksakov
  gather_facts: no
  tasks:
    - name: Loading hosts vars
      include_vars:
        file: "{{ playbook_dir }}/ips.yml"
        name: hosts

    - name: Insert configuration bind section
      lineinfile:
        path: /etc/redis.conf
        regexp: "bind 127.0.0.1"
        line: "bind {{ hosts['redis-5'] }}"

- name: Redis Cluster Install
  hosts: redis-6
  become: yes
  remote_user: dmaksakov
  gather_facts: no
  tasks:
    - name: Loading hosts vars
      include_vars:
        file: "{{ playbook_dir }}/ips.yml"
        name: hosts

    - name: Insert configuration bind section
      lineinfile:
        path: /etc/redis.conf
        regexp: "bind 127.0.0.1"
        line: "bind {{ hosts['redis-6'] }}"

- name: Enable redis.service
  hosts: redis
  become: yes
  remote_user: dmaksakov
  gather_facts: no
  tasks:
    - name: Enable redis service
      service:
        name: redis
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Restart for all server
      reboot:

- name: Create redis cluster
  hosts: redis-1
  become: yes
  remote_user: dmaksakov
  gather_facts: no
  tasks:
    - name: Loading hosts vars
      include_vars:
        file: "{{ playbook_dir }}/ips.yml"
        name: hosts

    - name: Waiting for all redis instances
      wait_for:
        host: "{{ item }}"
        port: 6379
        delay: 5
        timeout: 60
      loop:
        - "{{ hosts['redis-1'] }}"
        - "{{ hosts['redis-2'] }}"
        - "{{ hosts['redis-3'] }}"
        - "{{ hosts['redis-4'] }}"
        - "{{ hosts['redis-5'] }}"
        - "{{ hosts['redis-6'] }}"

    - name: Create redis cluster
      shell: echo yes | redis-cli --cluster create {{ hosts['redis-1'] }}:6379 {{ hosts['redis-2'] }}:6379 {{ hosts['redis-3'] }}:6379 {{ hosts['redis-4'] }}:6379 {{ hosts['redis-5'] }}:6379 {{ hosts['redis-6'] }}:6379 --cluster-replicas 1

    - name: Cluster info
      shell: redis-cli -c -h {{ hosts['redis-1'] }} -p 6379 cluster nodes
      register: cluster_info

    - debug:
        var: cluster_info.stdout_lines
